version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/node:14-browsers
    working_directory: ~/repo

    steps:
      - checkout

      # Attach the workspace for cache sharing between jobs
      - attach_workspace:
          at: ~/repo

      # Create the SSH directory and set the permissions
      - run: mkdir -p ~/.ssh && chmod 700 ~/.ssh

      # Add the SSH private key to the SSH directory
      - run: echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      # Set the GIT_SSH_COMMAND environment variable
      - run: echo -e "machine github.com\n  login $SSH_PRIVATE_KEY" > ~/.netrc && chmod 600 ~/.netrc
      - run: echo -e "#!/bin/sh\nexec /usr/bin/ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa \"\$@\"" > ~/.ssh/git-ssh-wrapper && chmod +x ~/.ssh/git-ssh-wrapper
      - run: export GIT_SSH_COMMAND="~/.ssh/git-ssh-wrapper"

      # Clone the repository containing the Next.js app
      - run: git clone https://github.com/mehmetaltugakgul/huawei-cloud-nextjs-app.git

      # Install NVM (Node Version Manager)
      - run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash

      # Activate NVM
      - run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

      # Install Node.js (version 14.17.4)
      - run: nvm install 14.17.4

      # Install Nginx web server
      - run: sudo apt-get update && sudo apt-get install -y nginx

      # Configure Nginx to serve the Next.js app
      - run: |
          echo 'server {
              listen 80;
              server_name 122.8.154.93; # Replace with your domain name
              location / {
                  proxy_pass http://localhost:3000; # Assuming your Next.js app is running on port 3000
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade \$http_upgrade;
                  proxy_set_header Connection "upgrade";
                  proxy_set_header Host \$host;
                  proxy_cache_bypass \$http_upgrade;
              }
          }' | sudo tee /etc/nginx/sites-available/122.8.154.93
          sudo ln -s /etc/nginx/sites-available/122.8.154.93 /etc/nginx/sites-enabled/
          sudo nginx -t
          sudo service nginx restart

      # Install dependencies and build the Next.js application
      - run:
          name: Install dependencies and Build Next.js application
          command: |
            cd huawei-cloud-nextjs-app # Replace with the path to your Next.js application
            npm install --force
            npm run build

      # Start the Next.js application
      - run:
          name: Start Next.js application
          command: |
            cd huawei-cloud-nextjs-app # Replace with the path to your Next.js application
            nohup npm run start &

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
