name: Deploy to Huawei Cloud ECS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code to the runner machine
      - name: Checkout repository
        uses: actions/checkout@v2

      # Upload the repository to the server via SCP using SSH
      - name: Upload repository to Huawei Cloud ECS
        uses: appleboy/ssh-action@master
        with:
          host: 190.92.217.211
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your private key as a secret in the GitHub repository settings
          port: 22  # Replace with the SSH port number if different (default is 22)
          script: |
            # Create a directory to store the application files
            mkdir -p ~/nextjs-app

            # Copy the build folder to the server using SCP
            scp -r path/to/your/nextjs/app/build/* ${{ secrets.SSH_USERNAME }}@190.92.217.211:~/nextjs-app/

      # SSH into the server and clone the repository
      - name: Clone GitHub repository on the server
        uses: appleboy/ssh-action@master
        with:
          host: your-huawei-cloud-ecs-ip
          username: your-ssh-username
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your private key as a secret in the GitHub repository settings
          port: 22  # Replace with the SSH port number if different (default is 22)
          script: |
            git clone https://github.com/your-username/your-repo.git ~/nextjs-repo  # Replace with your GitHub repository URL

      # Install dependencies and build Next.js application
      - name: Build Next.js app on the server
        uses: appleboy/ssh-action@master
        with:
          host: 190.92.217.211
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your private key as a secret in the GitHub repository settings
          port: 22  # Replace with the SSH port number if different (default is 22)
          script: |
            cd ~/nextjs-repo/path/to/your/nextjs/app
            npm install
            npm run build

      # SSH into the server and perform setup tasks
      - name: SSH into the server and setup Nginx
        uses: appleboy/ssh-action@master
        with:
          host: your-huawei-cloud-ecs-ip
          username: your-ssh-username
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your private key as a secret in the GitHub repository settings
          port: 22  # Replace with the SSH port number if different (default is 22)
          script: |
            # Install Nginx on the server (if not already installed)
            sudo apt-get update
            sudo apt-get install nginx -y

            # Configure Nginx to serve your Next.js application
            sudo rm /etc/nginx/sites-enabled/default
            sudo bash -c 'cat > /etc/nginx/sites-available/nextjs-app' << EOF
            server {
              listen 80 default_server;
              server_name _;
              location / {
                root /home/${{ secrets.SSH_USERNAME }}/nextjs-repo/path/to/your/nextjs/app/build;  # Replace with the path to the copied Next.js build folder
                index index.html;
              }
            }
            EOF

            sudo ln -s /etc/nginx/sites-available/nextjs-app /etc/nginx/sites-enabled/
            sudo nginx -t
            sudo systemctl restart nginx
