name: Deploy Next.js to Server
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    


    steps:
    
    - name: Deploy Next.js application
      run: |
        sudo apt install npm
        
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'  # You can specify the desired Node.js version here

    - name: Install SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add server to known hosts
      run: ssh-keyscan -H 190.92.217.211 >> ~/.ssh/known_hosts

    - name: Deploy Next.js application
      run: |
        sudo apt install nodejs
        sudo apt install npm
        sudo apt install curl
        ssh -i ~/.ssh/id_rsa root@190.92.217.211 "cd huawei-cloud-nextjs-app && npm install && npm run build && npm run start:prod"
