name: Deploy Next.js Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Add any other SSH configuration you might need, such as known_hosts, etc.

      - name: Install Node.js and npm
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm

      - name: Install Nginx
        run: |
          sudo apt-get install -y nginx

      - name: Configure Nginx
        run: |
          sudo bash -c 'cat << EOF > /etc/nginx/sites-available/122.8.154.93
          server {
              listen 80;
              server_name 122.8.154.93;

              location / {
                  proxy_pass http://localhost:3000; # Assuming your Next.js app is running on port 3000
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade \$http_upgrade;
                  proxy_set_header Connection "upgrade";
                  proxy_set_header Host \$host;
                  proxy_cache_bypass \$http_upgrade;
              }
          }
          EOF'

          sudo ln -s /etc/nginx/sites-available/122.8.154.93 /etc/nginx/sites-enabled/
          sudo nginx -t
          sudo service nginx restart

      - name: Clone the repository
        run: git clone https://github.com/mehmetaltugakgul/huawei-cloud-nextjs-app.git

      - name: Install dependencies and Build Next.js application
        run: |
          cd huawei-cloud-nextjs-app
          npm install --force
          npm run build

      - name: Start Next.js application
        run: |
          cd huawei-cloud-nextjs-app
          nohup npm run dev &
