name: Deploy Next.js to Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add server to known hosts
      run: ssh-keyscan -H 190.92.217.211 >> ~/.ssh/known_hosts

    - name: Deploy Next.js application
      run: |
        ssh -i ~/.ssh/id_rsa root@190.92.217.211 "git pull origin main && npm install && npm run build && npm run start:prod"
