name: Deploy to Huawei Cloud ECS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code to the runner machine
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install dependencies and build Next.js application
      - name: Build Next.js app
        run: |
          cd path/to/your/nextjs/app
          npm install
          npm run build

      # Upload the build folder to the server via SSH
      - name: Deploy to Huawei Cloud ECS
        uses: appleboy/scp-action@v1
        with:
          host: your-huawei-cloud-ecs-ip
          username: your-ssh-username
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your private key as a secret in the GitHub repository settings

      # SSH into the server and perform setup tasks
      - name: SSH into the server
        uses: appleboy/ssh-action@master
        with:
          host: 190.92.217.211
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your private key as a secret in the GitHub repository settings
          script: |
            # Install Nginx on the server (if not already installed)
            sudo apt-get update
            sudo apt-get install nginx -y

            # Configure Nginx to serve your Next.js application
            sudo rm /etc/nginx/sites-enabled/default
            sudo bash -c 'cat > /etc/nginx/sites-available/nextjs-app' << EOF
            server {
              listen 80 default_server;
              server_name _;
              location / {
                root /path/to/your/nextjs/app/build;  # Replace with the path to your Next.js build folder
                index index.html;
              }
            }
            EOF

            sudo ln -s /etc/nginx/sites-available/nextjs-app /etc/nginx/sites-enabled/
            sudo nginx -t
            sudo systemctl restart nginx
